### ISSUE TITLE
bearer parameter from the Import Manifest is not used

### ISSUE THREAD

**Issue by jwjahns** [inferno-framework/uds-plus-test-kit#22]
Hello,

The "Import Manifest" tests do not seem to parse the "bearer" parameter (`parameter:udsData.part:importAccessToken`) when making requests.
https://github.com/inferno-framework/uds-plus-test-kit/blob/4999db590f7cee5d3595051fac8ab44cc3783c75/lib/uds_plus_test_kit/manifest_tests/read_data_test.rb#L40-L47

As a result, URLs that require authentication cannot be tested.

**Comment by ljtucker** [comment]
Hi @jwjahns, unfortunately this Inferno kit is not meant to test any of the authentication steps of the IG's workflow. Rather, it is simply meant as a structure-conformance validator for the resources. Because of this, all provided URLs must be public in order to be accessed.

**Comment by hbader93** [comment]
This doesn't make sense to me. 

A big part of the UDS+ workflow is if a submitter has a secured endpoint (which will probably be the norm), they need to send in some way of having HRSA grab their Bulk Files. I think it also could be argued that that is part of structure-conformance.

But at the end of the day, what this boils down to is - to verify that UDS+ works, hospitals are generally going to have to connect with HRSA's sandbox. If this can successfully process / request data from secured URLs, that's one fewer thing that needs to be worked out when each hospital attempts to connect to HRSA for onboarding.
