### ISSUE TITLE
Wrong Display Name Errors

### ISSUE THREAD

**Issue by anthonygalba** [inferno-framework/uds-plus-test-kit#32]
In v1.1.0 of the test kit, you switched to an external terminology server (https://tx.fhir.org/r4/) to validate displays for many external code systems.
We are seeing a lot of errors for minor differences in display names. Example:

Condition/scFNY5PWmSvyv6S2sHQmltjtGnxyIo2uld.m9dOYh4QHqimdqx9gkRZQfN-KjrF5: Condition.code.coding[2].display: Wrong Display Name 'Asymptomatic human immunodeficiency virus (hiv) infection status' for http://hl7.org/fhir/sid/icd-10-cm#Z21. Valid display is 'Asymptomatic human immunodeficiency virus [HIV] infection status' (for the language(s) '--')

Can you lower those to warnings instead of errors? Display name shouldn't drive any actual functionality, so minor differences shouldn't really matter.

**Comment by arscan** [comment]
This is the default for the HL7 FHIR Validator, which is the authoritative validator in the community.  It does provide an option to downgrade these to warnings though.  In this test kit code, we'd just add:

```ruby
          cli_context do
            displayWarnings true
          end
```

...to this block:

https://github.com/inferno-framework/uds-plus-test-kit/blob/7527f78a8073409bb19ed74ed31293eed31fd0b0/lib/uds_plus_test_kit/uds_plus_test_suite.rb#L21-L34

I don't personally feel like this is worthy of an 'error' in this context either, but we generally just go with the default validator behavior.

Any opinions on this @ljtucker?  I see we filter out plenty of validator messages manually in this test kit, so it seems like the preference here is to clear out questionable errors.

**Comment by ljtucker** [comment]
Hi @arscan, we're in agreement on the UDS+ side, let's lower that from an error to a warning, thanks!

**Comment by arscan** [comment]
Sure, we can make that change real quick.

**Comment by anthonygalba** [comment]
Thanks for the quick fix!
