### ISSUE TITLE
Set Manifest read/validate input to optional for Resource-specific test group

### ISSUE THREAD

**Issue by ljtucker** [inferno-framework/uds-plus-test-kit#4]
From email exchange w/ @arscan:

> I was going over the UDS+ kit this morning and noticed a bug I overlooked when I passed the kit off to your team (I added a last-minute input option to one of the tests and forgot to set it to optional). I updated the bug and pushed the changes to my repo, but I'm not sure if your team forked their own version of the kit and won't see the change. Could your team integrate the fix into the kit on their end? Thank you, and sorry for the last-minute update.

I have checked out a branch for this repo and transferred the changes to it, but I do not have editor permissions for this repo, so I can't push the branch and make a pull request for it. Could I be given editor permissions, or could someone who already has permission move the changes from the original repo to this one? (The commit from the original repo is [here](https://github.com/ljtucker/UDS-Plus-Test-Kit/commit/058d0b5511ee32925bb8b5bf05de8e471092b858#diff-51cd3d944c1f2f0ff62b32e8586a81160ec3a20af8c9092f8c959837940a0617), if you would like to look over the changes before proceeding).

**Comment by ljtucker** [comment]
The exact changes I made are:
- Set the validate manifest test to omit_if there was no manifest resource inputted
- Create a copy of the read_manifest test (read_manifest_ind test) that is an exact copy of the original read test, but with the input set to optional, and for the test to be omitted if no input was given
- Modify the Resource test group to reference the read_manifest_ind test instead of the original read_manifest test

**Comment by arscan** [comment]
Hi @ljtucker -- I pulled in your changes over into #5 just to get it done quick.  Let me know if I missed anything there.

There are a number of options for how we can manage this in the future (add you as a maintainer, or if not just have you 'fork' this repo and issue pull requests using GitHub's tools).
